parameters:
  workingDirectory: ''
  gradleWrapperFile: ''
  gradleOptions: ''
  javaHomeOption: ''
  jdkVersionOption: ''
  jdkArchitectureOption: ''
  testResultsFiles: ''
  tasks: ''
  
steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      workingDirectory: '${{paramters.workingDirectory}}'
      tasks: 'assembleDebug'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      testRunTitle: 'Android Unit Tests'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '11.0.10'
      jdkArchitectureOption: 'x64'

  - task: AndroidSigning@3
    inputs:
      apkFiles: '**/*.apk'
      apksignerKeystoreFile: 'android-debug.keystore'
      apksignerKeystorePassword: 'android'
      apksignerKeystoreAlias: 'android'
      apksignerKeyPassword: 'android'
