name: Android Build with Gradle
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: |
          build/*/*.aab
          app/*/*.aab
          */*.aab
          */*.apk
          
    - name: Run build with Gradle wrapper
      run: ./gradlew build -stacktrace

    - name: Check Current Path
      run: |
        yarn install
        find . -type f -name "*.aab"
        pwd
          
    - name: Signing Android with Gradle
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: /home/runner/work/AndroidDemoApplication/AndroidDemoApplication
        signingKeyBase64: '${{ secrets.SIGNING_KEY }}'
        alias: '${{ secrets.ALIAS }}'
        keyStorePassword: '${{ secrets.KEY_STORE_PASSWORD }}'
        keyPassword: '${{ secrets.KEY_PASSWORD }}'

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/artifacts/

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Android Build Artifacts to App Center
        uses: devussy/AppCenter-Distribute-Github-Action@v1.0.2
        with:
          token: ad7c1190b680df01a8cadfdde0b64a6ef37be32b
          app: chetan.chaudhari-nagarro.com/android-demo-app
          file: ./build/*/*.apk
          group: Chetan
          releaseNotes: Initial Release Version 1.0
          silent: true
