# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Android Build with Gradle - $(date:yyyy).$(Month)$(rev:.r)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3    
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: build
        build-root-directory: './app/'
      
    - name: Run build with Gradle wrapper
      run: ./gradlew build --scan
      
     #tasks: 'assembleRelease assembleDebugAndroidTest'
    
    - name: Check Current Path
    - run: |
        yarn install
        ls -R ./
        pwd

    - name: Signing Android with Gradle
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: '**/*.apk'
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }} # optional
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/artifacts/
        
    - name: Deploy Android Build Artifacts to App Center
      uses: devussy/AppCenter-Distribute-Github-Action@v1.0.2
      with:
        token: 'ad7c1190b680df01a8cadfdde0b64a6ef37be32b'
        app: 'chetan.chaudhari-nagarro.com/android-demo-app'
        file: './build/*/*.apk'
        group: Chetan
        releaseNotes: 'Initial Release Version 1.0'
        silent: true
