name: Build, code quality, tests 

'on':
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: build release 
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease
      
    - name: App Center Distribute
      uses: devussy/AppCenter-Distribute-Github-Action@master
      with:
        app: chetan.chaudhari-nagarro.com/android-demo-app
        token: ${{secrets.APP_CENTER_API_TOKEN_KEY}}
        group: Chetan
        file: ./*.apk
        silent: false
