name: Caching Test

on: push

jobs:
  build:
    runs-on: 'Ubuntu-Latest'

    steps:
    - uses: actions/checkout@v2

    - name: Enable Cache
      id: cache-action
      uses: actions/cache@v2
      with:
        path: cache-folder
        key: ${{ runner.os }}-cache-key

    - name: Use or generate the cache
      if: steps.cache-action.outputs.cache-hit != 'true'
      run: mkdir cache-folder && touch cache-folder/hello.txt

    - name: Verify we have our cached file
      run: ls cache-folder
