name: Set Secrets

on: [push]

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read secrets from secrets.json
        run: |
          secrets=$(cat secrets.json | jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]')
          for secret in $secrets; do
            echo "$secret" >> $GITHUB_ENV
          done
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
