name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Playwright
      run: |
        npx playwright install --with-deps

    - name: Install Playwright 2
      run: |
        sudo apt-get update && npx playwright install --with-deps
